apiVersion: v1
kind: Service
metadata:
  name: color
  labels:
    app: color-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: color-service
